<a href="https://colab.research.google.com/github/DianaRivas98/Proyecto-Big-Data/blob/main/Proyecto_BigData___1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install rpy2

Requirement already satisfied: rpy2 in /usr/local/lib/python3.10/dist-packages (3.4.2)
Requirement already satisfied: cffi>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from rpy2) (1.16.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from rpy2) (3.1.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from rpy2) (2023.3.post1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from rpy2) (5.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.10.0->rpy2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->rpy2) (2.1.3)

In [2]:
%load_ext rpy2.ipython

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
url= '/content/drive/MyDrive/Big_Data/Proyecto_Big_Data_(1).xlsx'

In [6]:
import pandas as pd
df=pd.read_excel(url)

In [7]:
df.head()

,Unnamed: 0,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License
0,0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649.0,2.138484e+09,2923706026,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000.0,1.941066e+09,2799439100,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767.0,1.636175e+09,2320250281,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608.0,1.590451e+09,2264743305,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225.0,1.134648e+09,2071310218,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

In [8]:
df['Year'] = df['Year'].astype(int)

In [ ]:
df.describe()

,Unnamed: 0,Year,Domestic Sales (in $),International Sales (in $),World Wide Sales (in $)
count,1000.000000,995.000000,9.950000e+02,9.950000e+02,9.950000e+02
mean,499.500000,2008.167839,1.648976e+08,2.646278e+08,4.236093e+08
std,288.819436,10.601003,1.199746e+08,2.137490e+08,3.060077e+08
min,0.000000,1937.000000,6.752000e+03,2.450000e+07,1.799689e+08
25%,249.750000,2002.000000,9.585548e+07,1.327110e+08,2.276657e+08
50%,499.500000,2010.000000,1.351891e+08,1.946035e+08,3.197157e+08
75%,749.250000,2016.000000,1.987321e+08,3.200089e+08,4.863644e+08
max,999.000000,2023.000000,9.366622e+08,2.138484e+09,2.923706e+09

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1000 non-null   int64
 1   Title                       1000 non-null   object
 2   Movie Info                  1000 non-null   object
 3   Year                        1000 non-null   int64
 4   Distributor                 994 non-null    object
 5   Budget (in $)               995 non-null    object
 6   Domestic Opening (in $)     995 non-null    object
 7   Domestic Sales (in $)       995 non-null    float64
 8   International Sales (in $)  995 non-null    float64
 9   World Wide Sales (in $)     1000 non-null   int64
 10  Release Date                995 non-null    object
 11  Genre                       995 non-null    object
 12  Running Time                995 non-null    object
 13  License                     938 non-null    object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [10]:
%%R
install.packages("tidyverse")

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/tidyverse_2.0.0.tar.gz'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Content type 'application/x-gzip'
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  length 704618 bytes (688 KB)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: downloaded 688 KB


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The downloaded source packages are in
	‘/tmp/Rtmpg5bbO9/downloaded_packages’
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

In [11]:
%%R
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [12]:
%%R
 install.packages("dplyr")

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/dplyr_1.1.3.tar.gz'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Content type 'application/x-gzip'
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  length 1083635 bytes (1.0 MB)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: downloaded 1.0 MB


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The downloaded source packages are in
	‘/tmp/Rtmpg5bbO9/downloaded_packages’
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

In [13]:
%%R
library ("dplyr")

In [14]:
%%R
data(df)

In [15]:
%%R

df%>%head()

1 function (x, df1, df2, ncp, log = FALSE)
2 {
3     if (missing(ncp))
4         .Call(C_df, x, df1, df2, log)
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }

In [33]:
filtered1_df = df[df['Year'] == 2015]

In [28]:
filtered2_df = df[df['Genre'] == "Action"]

In [29]:
filtered3_df = df[df['Running Time'] == "2 hr 8 min "]

In [36]:
filtered_df = df[df['International Sales (in $)']=="2.138484e+09"]

In [37]:
print(filtered_df)

Empty DataFrame
Columns: [Unnamed: 0, Title, Movie Info, Year, Distributor, Budget (in $), Domestic Opening (in $), Domestic Sales (in $), International Sales (in $), World Wide Sales (in $), Release Date, Genre, Running Time, License]
Index: []

In [34]:
print(filtered1_df)

     Unnamed: 0                                       Title  \
4             4  Star Wars: Episode VII - The Force Awakens
7             7                              Jurassic World
10           10                                   Furious 7
14           14                     Avengers: Age of Ultron
25           25                                     Minions
77           77                                     Spectre
86           86                                  Inside Out
149         149          Mission: Impossible - Rogue Nation
162         162       The Hunger Games: Mockingjay - Part 2
167         167                                 The Martian
194         194                        Fifty Shades of Grey
212         212                                  Cinderella
218         218                                The Revenant
232         232                                     Ant-Man
260         260                        Hotel Transylvania 2
264         264                                 San Andreas
299         299                          Terminator Genisys
361         361                                Monster Hunt
363         363                                        Home
375         375                          Mad Max: Fury Road
416         416                              The Karate Kid
473         473                           The Good Dinosaur
488         488    The SpongeBob Movie: Sponge Out of Water
512         512              Maze Runner: The Scorch Trials
553         553             The Divergent Series: Insurgent
578         578                             Pitch Perfect 2
637         637                      Mojin: The Lost Legend
645         645                           Lost in Hong Kong
678         678                           The Peanuts Movie
688         688                                      Pixels
696         696                                Daddy's Home
720         720                                         Spy
724         724      Alvin and the Chipmunks: The Road Chip
743         743                           Goodbye Mr. Loser
803         803                                       Ted 2
843         843                                Tomorrowland
876         876                                     Everest
884         884                      Straight Outta Compton
919         919                                  The Intern
955         955                               Jian Bing Man
970         970                           Jupiter Ascending

                                            Movie Info  Year  \
4    As a new threat to the galaxy rises, Rey, a de...  2015
7    A new theme park, built on the original site o...  2015
10   Deckard Shaw seeks revenge against Dominic Tor...  2015
14   When Tony Stark and Bruce Banner try to jump-s...  2015
25   Minions Stuart, Kevin, and Bob are recruited b...  2015
77   A cryptic message from James Bond's past sends...  2015
86   After young Riley is uprooted from her Midwest...  2015
149  Ethan and his team take on their most impossib...  2015
162  Katniss and a team of rebels from District 13 ...  2015
167  An astronaut becomes stranded on Mars after hi...  2015
194  Literature student Anastasia Steele's life cha...  2015
212  When her father unexpectedly dies, young Ella ...  2015
218  A frontiersman on a fur trading expedition in ...  2015
232  Armed with a super-suit with the astonishing a...  2015
260  Dracula and his friends try to bring out the m...  2015
264  In the aftermath of a massive earthquake in Ca...  2015
299  When John Connor, leader of the human resistan...  2015
361  Human and monsters have lived in their separat...  2015
363  An alien on the run from his own people makes ...  2015
375  In a post-apocalyptic wasteland, a woman rebel...  2015
416  Work causes a single mother to move to China w...  2015
473  In a world where dinosaurs and humans live sid...  2015
488  When a diabolical pirate above the sea steals ...  2015
512  After having escaped the Maze, the Gladers now...  2015
553  Beatrice Prior must confront her inner demons ...  2015
578  After a humiliating command performance at The...  2015
637  In 1969 PRChina, two men survive a supernatura...  2015
645  The film follows Xu Lai, a former artist whose...  2015
678  Snoopy embarks upon his greatest mission as he...  2015
688  When aliens misinterpret video feeds of classi...  2015
696  Brad Whitaker is a radio host trying to get hi...  2015
720  A desk-bound CIA analyst volunteers to go unde...  2015
724  The Chipmunks believe that Dave plans to propo...  2015
743  After attending a wedding of his high school c...  2015
803  Newlywed couple Ted and Tami-Lynn want to have...  2015
843  Bound by a shared destiny, a teen bursting wit...  2015
876  The story of New Zealand mountaineer Rob Hall,...  2015
884  The rap group NWA emerges from the mean street...  2015
919  Seventy-year-old widower Ben Whittaker has dis...  2015
955  A story of a disgraced actor struggling to fin...  2015
970  A young woman discovers her destiny as an heir...  2015

                             Distributor                 Budget (in $)  \
4    Walt Disney Studios Motion Pictures                     245000000
7                     Universal Pictures                     150000000
10                    Universal Pictures                     190000000
14   Walt Disney Studios Motion Pictures                     250000000
25                    Universal Pictures                      74000000
77     Sony Pictures Entertainment (SPE)                     245000000
86   Walt Disney Studios Motion Pictures                     175000000
149                   Paramount Pictures                     150000000
162                            Lionsgate                     160000000
167                Twentieth Century Fox                     108000000
194                   Universal Pictures                      40000000
212  Walt Disney Studios Motion Pictures                      95000000
218                Twentieth Century Fox                     135000000
232  Walt Disney Studios Motion Pictures                     130000000
260    Sony Pictures Entertainment (SPE)                      80000000
264                         Warner Bros.                     110000000
299                   Paramount Pictures                     155000000
361                             FilmRise     July 16 2015 (APAC China)
363                Twentieth Century Fox                     135000000
375                         Warner Bros.                     150000000
416                                  NaN                           NaN
473  Walt Disney Studios Motion Pictures  November 25 2015 (7 markets)
488                   Paramount Pictures                      74000000
512                Twentieth Century Fox                      61000000
553                            Lionsgate                     110000000
578                   Universal Pictures                      29000000
637            Well Go USA Entertainment                      37000000
645            Well Go USA Entertainment      September 24 2015 (APAC)
678                Twentieth Century Fox                      99000000
688    Sony Pictures Entertainment (SPE)                      88000000
696                   Paramount Pictures       December 24 2015 (APAC)
720                Twentieth Century Fox                      65000000
724                Twentieth Century Fox   December 18 2015 (Domestic)
743         China Lion Film Distribution     September 25 2015 (China)
803                   Universal Pictures                      68000000
843  Walt Disney Studios Motion Pictures                     190000000
876                   Universal Pictures                      55000000
884                   Universal Pictures                      28000000
919                         Warner Bros.                      35000000
955                July 17, 2015 (China)                      28000000
970                         Warner Bros.                     176000000

    Domestic Opening (in $)  Domestic Sales (in $)  \
4                 247966675            936662225.0
7                 208806270            653406625.0
10                147187040            353007020.0
14                191271109            459005868.0
25                115718405            336045770.0
77                 70403148            200074609.0
86                 90440272            356921711.0
149                55520089            195042377.0
162               102665981            281723902.0
167                54308575            228433663.0
194                85171450            166167230.0
212                67877361            201151353.0
218                  474560            183637894.0
232                57225526            180202163.0
260                48464322            169700110.0
264                54588173            155190832.0
299                27018486             89760956.0
361                   21074                32766.0
363                52107731            177397510.0
375                45428128            154280290.0
416                     NaN                    NaN
473                39155217            123087120.0
488                55365012            162994032.0
512                30316510             81697192.0
553                52263680            130179072.0
578                69216890            184296230.0
637                  279974              1243810.0
645                  537736              1302281.0
678                44213073            130178411.0
688                24011616             78747585.0
696                38740203            150357137.0
720                29085719            110825712.0
724                14287159             85886987.0
743                  363949              1293626.0
803                33507870             81476385.0
843                33028165             93436322.0
876                 7222035             43482270.0
884                60200180            161197785.0
919                17728313             75764672.0
955             1 hr 53 min            186699768.0
970                18372372             47387723.0

     International Sales (in $)  World Wide Sales (in $)         Release Date  \
4                  1.134648e+09               2071310218            16-Dec-15
7                  1.018131e+09               1671537444  2015-06-10 00:00:00
10                 1.162334e+09               1515341399             1-Apr-15
14                 9.460122e+08               1405018048            22-Apr-15
25                 8.233989e+08               1159444662             9-Apr-15
77                 6.806307e+08                880705312  2015-10-26 00:00:00
86                 5.019263e+08                858848019  2015-06-10 00:00:00
149                4.876743e+08                682716636  2015-07-24 00:00:00
162                3.717044e+08                653428261  2015-11-18 00:00:00
167                4.021872e+08                630620818  2015-09-30 00:00:00
194                4.034842e+08                569651467  2015-02-11 00:00:00
212                3.412070e+08                542358331  2015-03-11 00:00:00
218                3.493126e+08                532950503            25-Dec-15
232                3.391098e+08                519311965  2015-07-10 00:00:00
260                3.054866e+08                475186706  2015-09-21 00:00:00
264                3.188183e+08                474009154  2015-05-22 00:00:00
299                3.508426e+08                440603537  2015-06-25 00:00:00
361                3.870207e+08                387053506  2007-06-26 00:00:00
363                2.086441e+08                386041607  2015-03-19 00:00:00
375                2.258000e+08                380080290  2015-05-07 00:00:00
416                         NaN                     2000                  NaN
473                2.091206e+08                332207671  1989-11-22 00:00:00
488                1.621920e+08                325186032            28-Jan-15
512                2.305989e+08                312296056  2015-09-09 00:00:00
553                1.668235e+08                297002527  2015-03-18 00:00:00
578                1.028478e+08                287144079  2015-05-07 00:00:00
637                2.581246e+08                259368448            17-Dec-15
645                2.549816e+08                256283912            13-Aug-03
678                1.160547e+08                246233113  2015-10-29 00:00:00
688                1.661272e+08                244874809  2015-07-16 00:00:00
696                9.242900e+07                242786137  2002-11-08 00:00:00
720                1.248405e+08                235666219  2015-05-21 00:00:00
724                1.489116e+08                234798636  1999-06-25 00:00:00
743                2.268293e+08                228122928  2007-02-14 00:00:00
803                1.343872e+08                215863606  2015-06-19 00:00:00
843                1.155993e+08                209035668  2015-05-20 00:00:00
876                1.599453e+08                203427584  2015-09-10 00:00:00
884                4.043721e+07                201634991            14-Aug-15
919                1.188000e+08                194564672  2015-09-24 00:00:00
955                1.866998e+08                186797986  2005-02-02 00:00:00
970                1.365000e+08                183887723  2015-02-04 00:00:00

                                                 Genre Running Time License
4                    ['Action', 'Adventure', 'Sci-Fi']  2 hr 18 min   PG-13
7                    ['Action', 'Adventure', 'Sci-Fi']   2 hr 4 min   PG-13
10                     ['Action', 'Crime', 'Thriller']  2 hr 17 min   PG-13
14                   ['Action', 'Adventure', 'Sci-Fi']  2 hr 21 min   PG-13
25   ['Adventure', 'Animation', 'Comedy', 'Crime', ...  1 hr 31 min      PG
77                 ['Action', 'Adventure', 'Thriller']  2 hr 28 min   PG-13
86   ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 35 min      PG
149                ['Action', 'Adventure', 'Thriller']  2 hr 11 min   PG-13
162      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 17 min   PG-13
167                   ['Adventure', 'Drama', 'Sci-Fi']  2 hr 24 min   PG-13
194                   ['Drama', 'Romance', 'Thriller']   2 hr 5 min       R
212  ['Adventure', 'Drama', 'Family', 'Fantasy', 'R...  1 hr 45 min      PG
218        ['Action', 'Adventure', 'Drama', 'Western']  2 hr 36 min       R
232                     ['Action', 'Comedy', 'Sci-Fi']  1 hr 57 min   PG-13
260  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 29 min      PG
264                ['Action', 'Adventure', 'Thriller']  1 hr 54 min   PG-13
299      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']   2 hr 6 min   PG-13
361                             ['Action', 'Thriller']   2 hr 8 min   PG-13
363  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 34 min      PG
375      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']         2 hr       R
416                                                NaN          NaN     NaN
473                  ['Adventure', 'Comedy', 'Sci-Fi']  1 hr 48 min     NaN
488  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 32 min      PG
512      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 11 min   PG-13
553      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  1 hr 59 min   PG-13
578                                ['Comedy', 'Music']  1 hr 55 min   PG-13
637  ['Action', 'Adventure', 'Drama', 'Fantasy', 'H...   2 hr 7 min     NaN
645                   ['Drama', 'Mystery', 'Thriller']  1 hr 48 min   PG-13
678  ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 28 min       G
688          ['Action', 'Comedy', 'Fantasy', 'Sci-Fi']  1 hr 45 min   PG-13
696                                 ['Drama', 'Music']  1 hr 50 min       R
720                               ['Action', 'Comedy']         2 hr       R
724                                ['Comedy', 'Drama']  1 hr 33 min   PG-13
743                  ['Action', 'Fantasy', 'Thriller']  1 hr 50 min   PG-13
803                                         ['Comedy']  1 hr 55 min       R
843  ['Action', 'Adventure', 'Family', 'Fantasy', '...  2 hr 10 min      PG
876  ['Action', 'Adventure', 'Biography', 'Drama', ...   2 hr 1 min   PG-13
884         ['Biography', 'Drama', 'History', 'Music']  2 hr 27 min       R
919                                ['Comedy', 'Drama']   2 hr 1 min   PG-13
955         ['Biography', 'Drama', 'Music', 'Romance']  2 hr 16 min   PG-13
970                  ['Action', 'Adventure', 'Sci-Fi']   2 hr 7 min   PG-13

In [31]:
print(filtered2_df)

Empty DataFrame
Columns: [Unnamed: 0, Title, Movie Info, Year, Distributor, Budget (in $), Domestic Opening (in $), Domestic Sales (in $), International Sales (in $), World Wide Sales (in $), Release Date, Genre, Running Time, License]
Index: []

In [32]:
print(filtered3_df)

Empty DataFrame
Columns: [Unnamed: 0, Title, Movie Info, Year, Distributor, Budget (in $), Domestic Opening (in $), Domestic Sales (in $), International Sales (in $), World Wide Sales (in $), Release Date, Genre, Running Time, License]
Index: []

In [21]:
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2018)]

In [18]:
print(filtered_df)

     Unnamed: 0                                       Title  \
4             4  Star Wars: Episode VII - The Force Awakens
7             7                              Jurassic World
10           10                                   Furious 7
14           14                     Avengers: Age of Ultron
25           25                                     Minions
77           77                                     Spectre
86           86                                  Inside Out
149         149          Mission: Impossible - Rogue Nation
162         162       The Hunger Games: Mockingjay - Part 2
167         167                                 The Martian
194         194                        Fifty Shades of Grey
212         212                                  Cinderella
218         218                                The Revenant
232         232                                     Ant-Man
260         260                        Hotel Transylvania 2
264         264                                 San Andreas
299         299                          Terminator Genisys
361         361                                Monster Hunt
363         363                                        Home
375         375                          Mad Max: Fury Road
416         416                              The Karate Kid
473         473                           The Good Dinosaur
488         488    The SpongeBob Movie: Sponge Out of Water
512         512              Maze Runner: The Scorch Trials
553         553             The Divergent Series: Insurgent
578         578                             Pitch Perfect 2
637         637                      Mojin: The Lost Legend
645         645                           Lost in Hong Kong
678         678                           The Peanuts Movie
688         688                                      Pixels
696         696                                Daddy's Home
720         720                                         Spy
724         724      Alvin and the Chipmunks: The Road Chip
743         743                           Goodbye Mr. Loser
803         803                                       Ted 2
843         843                                Tomorrowland
876         876                                     Everest
884         884                      Straight Outta Compton
919         919                                  The Intern
955         955                               Jian Bing Man
970         970                           Jupiter Ascending

                                            Movie Info  Year  \
4    As a new threat to the galaxy rises, Rey, a de...  2015
7    A new theme park, built on the original site o...  2015
10   Deckard Shaw seeks revenge against Dominic Tor...  2015
14   When Tony Stark and Bruce Banner try to jump-s...  2015
25   Minions Stuart, Kevin, and Bob are recruited b...  2015
77   A cryptic message from James Bond's past sends...  2015
86   After young Riley is uprooted from her Midwest...  2015
149  Ethan and his team take on their most impossib...  2015
162  Katniss and a team of rebels from District 13 ...  2015
167  An astronaut becomes stranded on Mars after hi...  2015
194  Literature student Anastasia Steele's life cha...  2015
212  When her father unexpectedly dies, young Ella ...  2015
218  A frontiersman on a fur trading expedition in ...  2015
232  Armed with a super-suit with the astonishing a...  2015
260  Dracula and his friends try to bring out the m...  2015
264  In the aftermath of a massive earthquake in Ca...  2015
299  When John Connor, leader of the human resistan...  2015
361  Human and monsters have lived in their separat...  2015
363  An alien on the run from his own people makes ...  2015
375  In a post-apocalyptic wasteland, a woman rebel...  2015
416  Work causes a single mother to move to China w...  2015
473  In a world where dinosaurs and humans live sid...  2015
488  When a diabolical pirate above the sea steals ...  2015
512  After having escaped the Maze, the Gladers now...  2015
553  Beatrice Prior must confront her inner demons ...  2015
578  After a humiliating command performance at The...  2015
637  In 1969 PRChina, two men survive a supernatura...  2015
645  The film follows Xu Lai, a former artist whose...  2015
678  Snoopy embarks upon his greatest mission as he...  2015
688  When aliens misinterpret video feeds of classi...  2015
696  Brad Whitaker is a radio host trying to get hi...  2015
720  A desk-bound CIA analyst volunteers to go unde...  2015
724  The Chipmunks believe that Dave plans to propo...  2015
743  After attending a wedding of his high school c...  2015
803  Newlywed couple Ted and Tami-Lynn want to have...  2015
843  Bound by a shared destiny, a teen bursting wit...  2015
876  The story of New Zealand mountaineer Rob Hall,...  2015
884  The rap group NWA emerges from the mean street...  2015
919  Seventy-year-old widower Ben Whittaker has dis...  2015
955  A story of a disgraced actor struggling to fin...  2015
970  A young woman discovers her destiny as an heir...  2015

                             Distributor                 Budget (in $)  \
4    Walt Disney Studios Motion Pictures                     245000000
7                     Universal Pictures                     150000000
10                    Universal Pictures                     190000000
14   Walt Disney Studios Motion Pictures                     250000000
25                    Universal Pictures                      74000000
77     Sony Pictures Entertainment (SPE)                     245000000
86   Walt Disney Studios Motion Pictures                     175000000
149                   Paramount Pictures                     150000000
162                            Lionsgate                     160000000
167                Twentieth Century Fox                     108000000
194                   Universal Pictures                      40000000
212  Walt Disney Studios Motion Pictures                      95000000
218                Twentieth Century Fox                     135000000
232  Walt Disney Studios Motion Pictures                     130000000
260    Sony Pictures Entertainment (SPE)                      80000000
264                         Warner Bros.                     110000000
299                   Paramount Pictures                     155000000
361                             FilmRise     July 16 2015 (APAC China)
363                Twentieth Century Fox                     135000000
375                         Warner Bros.                     150000000
416                                  NaN                           NaN
473  Walt Disney Studios Motion Pictures  November 25 2015 (7 markets)
488                   Paramount Pictures                      74000000
512                Twentieth Century Fox                      61000000
553                            Lionsgate                     110000000
578                   Universal Pictures                      29000000
637            Well Go USA Entertainment                      37000000
645            Well Go USA Entertainment      September 24 2015 (APAC)
678                Twentieth Century Fox                      99000000
688    Sony Pictures Entertainment (SPE)                      88000000
696                   Paramount Pictures       December 24 2015 (APAC)
720                Twentieth Century Fox                      65000000
724                Twentieth Century Fox   December 18 2015 (Domestic)
743         China Lion Film Distribution     September 25 2015 (China)
803                   Universal Pictures                      68000000
843  Walt Disney Studios Motion Pictures                     190000000
876                   Universal Pictures                      55000000
884                   Universal Pictures                      28000000
919                         Warner Bros.                      35000000
955                July 17, 2015 (China)                      28000000
970                         Warner Bros.                     176000000

    Domestic Opening (in $)  Domestic Sales (in $)  \
4                 247966675            936662225.0
7                 208806270            653406625.0
10                147187040            353007020.0
14                191271109            459005868.0
25                115718405            336045770.0
77                 70403148            200074609.0
86                 90440272            356921711.0
149                55520089            195042377.0
162               102665981            281723902.0
167                54308575            228433663.0
194                85171450            166167230.0
212                67877361            201151353.0
218                  474560            183637894.0
232                57225526            180202163.0
260                48464322            169700110.0
264                54588173            155190832.0
299                27018486             89760956.0
361                   21074                32766.0
363                52107731            177397510.0
375                45428128            154280290.0
416                     NaN                    NaN
473                39155217            123087120.0
488                55365012            162994032.0
512                30316510             81697192.0
553                52263680            130179072.0
578                69216890            184296230.0
637                  279974              1243810.0
645                  537736              1302281.0
678                44213073            130178411.0
688                24011616             78747585.0
696                38740203            150357137.0
720                29085719            110825712.0
724                14287159             85886987.0
743                  363949              1293626.0
803                33507870             81476385.0
843                33028165             93436322.0
876                 7222035             43482270.0
884                60200180            161197785.0
919                17728313             75764672.0
955             1 hr 53 min            186699768.0
970                18372372             47387723.0

     International Sales (in $)  World Wide Sales (in $)         Release Date  \
4                  1.134648e+09               2071310218            16-Dec-15
7                  1.018131e+09               1671537444  2015-06-10 00:00:00
10                 1.162334e+09               1515341399             1-Apr-15
14                 9.460122e+08               1405018048            22-Apr-15
25                 8.233989e+08               1159444662             9-Apr-15
77                 6.806307e+08                880705312  2015-10-26 00:00:00
86                 5.019263e+08                858848019  2015-06-10 00:00:00
149                4.876743e+08                682716636  2015-07-24 00:00:00
162                3.717044e+08                653428261  2015-11-18 00:00:00
167                4.021872e+08                630620818  2015-09-30 00:00:00
194                4.034842e+08                569651467  2015-02-11 00:00:00
212                3.412070e+08                542358331  2015-03-11 00:00:00
218                3.493126e+08                532950503            25-Dec-15
232                3.391098e+08                519311965  2015-07-10 00:00:00
260                3.054866e+08                475186706  2015-09-21 00:00:00
264                3.188183e+08                474009154  2015-05-22 00:00:00
299                3.508426e+08                440603537  2015-06-25 00:00:00
361                3.870207e+08                387053506  2007-06-26 00:00:00
363                2.086441e+08                386041607  2015-03-19 00:00:00
375                2.258000e+08                380080290  2015-05-07 00:00:00
416                         NaN                     2000                  NaN
473                2.091206e+08                332207671  1989-11-22 00:00:00
488                1.621920e+08                325186032            28-Jan-15
512                2.305989e+08                312296056  2015-09-09 00:00:00
553                1.668235e+08                297002527  2015-03-18 00:00:00
578                1.028478e+08                287144079  2015-05-07 00:00:00
637                2.581246e+08                259368448            17-Dec-15
645                2.549816e+08                256283912            13-Aug-03
678                1.160547e+08                246233113  2015-10-29 00:00:00
688                1.661272e+08                244874809  2015-07-16 00:00:00
696                9.242900e+07                242786137  2002-11-08 00:00:00
720                1.248405e+08                235666219  2015-05-21 00:00:00
724                1.489116e+08                234798636  1999-06-25 00:00:00
743                2.268293e+08                228122928  2007-02-14 00:00:00
803                1.343872e+08                215863606  2015-06-19 00:00:00
843                1.155993e+08                209035668  2015-05-20 00:00:00
876                1.599453e+08                203427584  2015-09-10 00:00:00
884                4.043721e+07                201634991            14-Aug-15
919                1.188000e+08                194564672  2015-09-24 00:00:00
955                1.866998e+08                186797986  2005-02-02 00:00:00
970                1.365000e+08                183887723  2015-02-04 00:00:00

                                                 Genre Running Time License
4                    ['Action', 'Adventure', 'Sci-Fi']  2 hr 18 min   PG-13
7                    ['Action', 'Adventure', 'Sci-Fi']   2 hr 4 min   PG-13
10                     ['Action', 'Crime', 'Thriller']  2 hr 17 min   PG-13
14                   ['Action', 'Adventure', 'Sci-Fi']  2 hr 21 min   PG-13
25   ['Adventure', 'Animation', 'Comedy', 'Crime', ...  1 hr 31 min      PG
77                 ['Action', 'Adventure', 'Thriller']  2 hr 28 min   PG-13
86   ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 35 min      PG
149                ['Action', 'Adventure', 'Thriller']  2 hr 11 min   PG-13
162      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 17 min   PG-13
167                   ['Adventure', 'Drama', 'Sci-Fi']  2 hr 24 min   PG-13
194                   ['Drama', 'Romance', 'Thriller']   2 hr 5 min       R
212  ['Adventure', 'Drama', 'Family', 'Fantasy', 'R...  1 hr 45 min      PG
218        ['Action', 'Adventure', 'Drama', 'Western']  2 hr 36 min       R
232                     ['Action', 'Comedy', 'Sci-Fi']  1 hr 57 min   PG-13
260  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 29 min      PG
264                ['Action', 'Adventure', 'Thriller']  1 hr 54 min   PG-13
299      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']   2 hr 6 min   PG-13
361                             ['Action', 'Thriller']   2 hr 8 min   PG-13
363  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 34 min      PG
375      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']         2 hr       R
416                                                NaN          NaN     NaN
473                  ['Adventure', 'Comedy', 'Sci-Fi']  1 hr 48 min     NaN
488  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 32 min      PG
512      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 11 min   PG-13
553      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  1 hr 59 min   PG-13
578                                ['Comedy', 'Music']  1 hr 55 min   PG-13
637  ['Action', 'Adventure', 'Drama', 'Fantasy', 'H...   2 hr 7 min     NaN
645                   ['Drama', 'Mystery', 'Thriller']  1 hr 48 min   PG-13
678  ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 28 min       G
688          ['Action', 'Comedy', 'Fantasy', 'Sci-Fi']  1 hr 45 min   PG-13
696                                 ['Drama', 'Music']  1 hr 50 min       R
720                               ['Action', 'Comedy']         2 hr       R
724                                ['Comedy', 'Drama']  1 hr 33 min   PG-13
743                  ['Action', 'Fantasy', 'Thriller']  1 hr 50 min   PG-13
803                                         ['Comedy']  1 hr 55 min       R
843  ['Action', 'Adventure', 'Family', 'Fantasy', '...  2 hr 10 min      PG
876  ['Action', 'Adventure', 'Biography', 'Drama', ...   2 hr 1 min   PG-13
884         ['Biography', 'Drama', 'History', 'Music']  2 hr 27 min       R
919                                ['Comedy', 'Drama']   2 hr 1 min   PG-13
955         ['Biography', 'Drama', 'Music', 'Romance']  2 hr 16 min   PG-13
970                  ['Action', 'Adventure', 'Sci-Fi']   2 hr 7 min   PG-13