<a href="https://colab.research.google.com/github/DianaRivas98/Proyecto-Big-Data/blob/main/Proyecto_BigData___1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
!pip install rpy2

Requirement already satisfied: rpy2 in /usr/local/lib/python3.10/dist-packages (3.4.2)
Requirement already satisfied: cffi>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from rpy2) (1.16.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from rpy2) (3.1.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from rpy2) (2023.3.post1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from rpy2) (5.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.10.0->rpy2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->rpy2) (2.1.3)

In [63]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [94]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [95]:
url= '/content/drive/MyDrive/Big_Data/Proyecto_Big_Data_(1).xlsx'

In [96]:
import pandas as pd
df=pd.read_excel(url)

In [97]:
df.head()

,Unnamed: 0,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License
0,0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009.0,Twentieth Century Fox,237000000,77025481,785221649.0,2.138484e+09,2.923706e+09,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019.0,Walt Disney Studios Motion Pictures,356000000,357115007,858373000.0,1.941066e+09,2.799439e+09,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022.0,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767.0,1.636175e+09,2.320250e+09,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997.0,Paramount Pictures,200000000,28638131,674292608.0,1.590451e+09,2.264743e+09,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015.0,Walt Disney Studios Motion Pictures,245000000,247966675,936662225.0,1.134648e+09,2.071310e+09,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

In [98]:
df['Year'] = df['Year'].astype(int)

IntCastingNaNError: ignored

In [90]:
df.describe()

,Unnamed: 0,Year,Domestic Sales (in $),International Sales (in $),World Wide Sales (in $)
count,1000.000000,995.000000,9.950000e+02,9.950000e+02,9.950000e+02
mean,499.500000,2008.167839,1.648976e+08,2.646278e+08,4.236093e+08
std,288.819436,10.601003,1.199746e+08,2.137490e+08,3.060077e+08
min,0.000000,1937.000000,6.752000e+03,2.450000e+07,1.799689e+08
25%,249.750000,2002.000000,9.585548e+07,1.327110e+08,2.276657e+08
50%,499.500000,2010.000000,1.351891e+08,1.946035e+08,3.197157e+08
75%,749.250000,2016.000000,1.987321e+08,3.200089e+08,4.863644e+08
max,999.000000,2023.000000,9.366622e+08,2.138484e+09,2.923706e+09

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1000 non-null   int64
 1   Title                       1000 non-null   object
 2   Movie Info                  1000 non-null   object
 3   Year                        995 non-null    float64
 4   Distributor                 994 non-null    object
 5   Budget (in $)               995 non-null    object
 6   Domestic Opening (in $)     995 non-null    object
 7   Domestic Sales (in $)       995 non-null    float64
 8   International Sales (in $)  995 non-null    float64
 9   World Wide Sales (in $)     995 non-null    float64
 10  Release Date                995 non-null    object
 11  Genre                       995 non-null    object
 12  Running Time                995 non-null    object
 13  License                     938 non-null    object
dtypes: float64(4), int64(1), object(9)
memory usage: 109.5+ KB

In [ ]:
%%R
install.packages("tidyverse")

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/tidyverse_2.0.0.tar.gz'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Content type 'application/x-gzip'
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  length 704618 bytes (688 KB)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: downloaded 688 KB


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The downloaded source packages are in
	‘/tmp/RtmprThwvW/downloaded_packages’
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

In [76]:
%%R
library(tidyverse)

In [ ]:
%%R
 install.packages("dplyr")

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/dplyr_1.1.3.tar.gz'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Content type 'application/x-gzip'
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  length 1083635 bytes (1.0 MB)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: =
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: downloaded 1.0 MB


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The downloaded source packages are in
	‘/tmp/RtmprThwvW/downloaded_packages’
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

In [ ]:
%%R
library ("dplyr")

In [ ]:
%%R
data(df)

In [79]:
%%R

df%>%head()

1 function (x, df1, df2, ncp, log = FALSE)
2 {
3     if (missing(ncp))
4         .Call(C_df, x, df1, df2, log)
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }

In [ ]:
filtered_df = df[df['Year'] == 2015]

In [ ]:
print(filtered_df)

     Unnamed: 0                                       Title  \
4             4  Star Wars: Episode VII - The Force Awakens
7             7                              Jurassic World
10           10                                   Furious 7
14           14                     Avengers: Age of Ultron
25           25                                     Minions
77           77                                     Spectre
86           86                                  Inside Out
149         149          Mission: Impossible - Rogue Nation
162         162       The Hunger Games: Mockingjay - Part 2
167         167                                 The Martian
194         194                        Fifty Shades of Grey
212         212                                  Cinderella
218         218                                The Revenant
232         232                                     Ant-Man
260         260                        Hotel Transylvania 2
264         264                                 San Andreas
299         299                          Terminator Genisys
361         361                                Monster Hunt
363         363                                        Home
375         375                          Mad Max: Fury Road
473         473                           The Good Dinosaur
488         488    The SpongeBob Movie: Sponge Out of Water
512         512              Maze Runner: The Scorch Trials
553         553             The Divergent Series: Insurgent
578         578                             Pitch Perfect 2
637         637                      Mojin: The Lost Legend
645         645                           Lost in Hong Kong
678         678                           The Peanuts Movie
688         688                                      Pixels
696         696                                Daddy's Home
720         720                                         Spy
724         724      Alvin and the Chipmunks: The Road Chip
743         743                           Goodbye Mr. Loser
803         803                                       Ted 2
843         843                                Tomorrowland
876         876                                     Everest
884         884                      Straight Outta Compton
919         919                                  The Intern
955         955                               Jian Bing Man
970         970                           Jupiter Ascending

                                            Movie Info    Year  \
4    As a new threat to the galaxy rises, Rey, a de...  2015.0
7    A new theme park, built on the original site o...  2015.0
10   Deckard Shaw seeks revenge against Dominic Tor...  2015.0
14   When Tony Stark and Bruce Banner try to jump-s...  2015.0
25   Minions Stuart, Kevin, and Bob are recruited b...  2015.0
77   A cryptic message from James Bond's past sends...  2015.0
86   After young Riley is uprooted from her Midwest...  2015.0
149  Ethan and his team take on their most impossib...  2015.0
162  Katniss and a team of rebels from District 13 ...  2015.0
167  An astronaut becomes stranded on Mars after hi...  2015.0
194  Literature student Anastasia Steele's life cha...  2015.0
212  When her father unexpectedly dies, young Ella ...  2015.0
218  A frontiersman on a fur trading expedition in ...  2015.0
232  Armed with a super-suit with the astonishing a...  2015.0
260  Dracula and his friends try to bring out the m...  2015.0
264  In the aftermath of a massive earthquake in Ca...  2015.0
299  When John Connor, leader of the human resistan...  2015.0
361  Human and monsters have lived in their separat...  2015.0
363  An alien on the run from his own people makes ...  2015.0
375  In a post-apocalyptic wasteland, a woman rebel...  2015.0
473  In a world where dinosaurs and humans live sid...  2015.0
488  When a diabolical pirate above the sea steals ...  2015.0
512  After having escaped the Maze, the Gladers now...  2015.0
553  Beatrice Prior must confront her inner demons ...  2015.0
578  After a humiliating command performance at The...  2015.0
637  In 1969 PRChina, two men survive a supernatura...  2015.0
645  The film follows Xu Lai, a former artist whose...  2015.0
678  Snoopy embarks upon his greatest mission as he...  2015.0
688  When aliens misinterpret video feeds of classi...  2015.0
696  Brad Whitaker is a radio host trying to get hi...  2015.0
720  A desk-bound CIA analyst volunteers to go unde...  2015.0
724  The Chipmunks believe that Dave plans to propo...  2015.0
743  After attending a wedding of his high school c...  2015.0
803  Newlywed couple Ted and Tami-Lynn want to have...  2015.0
843  Bound by a shared destiny, a teen bursting wit...  2015.0
876  The story of New Zealand mountaineer Rob Hall,...  2015.0
884  The rap group NWA emerges from the mean street...  2015.0
919  Seventy-year-old widower Ben Whittaker has dis...  2015.0
955  A story of a disgraced actor struggling to fin...  2015.0
970  A young woman discovers her destiny as an heir...  2015.0

                             Distributor                 Budget (in $)  \
4    Walt Disney Studios Motion Pictures                     245000000
7                     Universal Pictures                     150000000
10                    Universal Pictures                     190000000
14   Walt Disney Studios Motion Pictures                     250000000
25                    Universal Pictures                      74000000
77     Sony Pictures Entertainment (SPE)                     245000000
86   Walt Disney Studios Motion Pictures                     175000000
149                   Paramount Pictures                     150000000
162                            Lionsgate                     160000000
167                Twentieth Century Fox                     108000000
194                   Universal Pictures                      40000000
212  Walt Disney Studios Motion Pictures                      95000000
218                Twentieth Century Fox                     135000000
232  Walt Disney Studios Motion Pictures                     130000000
260    Sony Pictures Entertainment (SPE)                      80000000
264                         Warner Bros.                     110000000
299                   Paramount Pictures                     155000000
361                             FilmRise     July 16 2015 (APAC China)
363                Twentieth Century Fox                     135000000
375                         Warner Bros.                     150000000
473  Walt Disney Studios Motion Pictures  November 25 2015 (7 markets)
488                   Paramount Pictures                      74000000
512                Twentieth Century Fox                      61000000
553                            Lionsgate                     110000000
578                   Universal Pictures                      29000000
637            Well Go USA Entertainment                      37000000
645            Well Go USA Entertainment      September 24 2015 (APAC)
678                Twentieth Century Fox                      99000000
688    Sony Pictures Entertainment (SPE)                      88000000
696                   Paramount Pictures       December 24 2015 (APAC)
720                Twentieth Century Fox                      65000000
724                Twentieth Century Fox   December 18 2015 (Domestic)
743         China Lion Film Distribution     September 25 2015 (China)
803                   Universal Pictures                      68000000
843  Walt Disney Studios Motion Pictures                     190000000
876                   Universal Pictures                      55000000
884                   Universal Pictures                      28000000
919                         Warner Bros.                      35000000
955                July 17, 2015 (China)                      28000000
970                         Warner Bros.                     176000000

    Domestic Opening (in $)  Domestic Sales (in $)  \
4                 247966675            936662225.0
7                 208806270            653406625.0
10                147187040            353007020.0
14                191271109            459005868.0
25                115718405            336045770.0
77                 70403148            200074609.0
86                 90440272            356921711.0
149                55520089            195042377.0
162               102665981            281723902.0
167                54308575            228433663.0
194                85171450            166167230.0
212                67877361            201151353.0
218                  474560            183637894.0
232                57225526            180202163.0
260                48464322            169700110.0
264                54588173            155190832.0
299                27018486             89760956.0
361                   21074                32766.0
363                52107731            177397510.0
375                45428128            154280290.0
473                39155217            123087120.0
488                55365012            162994032.0
512                30316510             81697192.0
553                52263680            130179072.0
578                69216890            184296230.0
637                  279974              1243810.0
645                  537736              1302281.0
678                44213073            130178411.0
688                24011616             78747585.0
696                38740203            150357137.0
720                29085719            110825712.0
724                14287159             85886987.0
743                  363949              1293626.0
803                33507870             81476385.0
843                33028165             93436322.0
876                 7222035             43482270.0
884                60200180            161197785.0
919                17728313             75764672.0
955             1 hr 53 min            186699768.0
970                18372372             47387723.0

     International Sales (in $)  World Wide Sales (in $)         Release Date  \
4                  1.134648e+09             2.071310e+09            16-Dec-15
7                  1.018131e+09             1.671537e+09  2015-06-10 00:00:00
10                 1.162334e+09             1.515341e+09             1-Apr-15
14                 9.460122e+08             1.405018e+09            22-Apr-15
25                 8.233989e+08             1.159445e+09             9-Apr-15
77                 6.806307e+08             8.807053e+08  2015-10-26 00:00:00
86                 5.019263e+08             8.588480e+08  2015-06-10 00:00:00
149                4.876743e+08             6.827166e+08  2015-07-24 00:00:00
162                3.717044e+08             6.534283e+08  2015-11-18 00:00:00
167                4.021872e+08             6.306208e+08  2015-09-30 00:00:00
194                4.034842e+08             5.696515e+08  2015-02-11 00:00:00
212                3.412070e+08             5.423583e+08  2015-03-11 00:00:00
218                3.493126e+08             5.329505e+08            25-Dec-15
232                3.391098e+08             5.193120e+08  2015-07-10 00:00:00
260                3.054866e+08             4.751867e+08  2015-09-21 00:00:00
264                3.188183e+08             4.740092e+08  2015-05-22 00:00:00
299                3.508426e+08             4.406035e+08  2015-06-25 00:00:00
361                3.870207e+08             3.870535e+08  2007-06-26 00:00:00
363                2.086441e+08             3.860416e+08  2015-03-19 00:00:00
375                2.258000e+08             3.800803e+08  2015-05-07 00:00:00
473                2.091206e+08             3.322077e+08  1989-11-22 00:00:00
488                1.621920e+08             3.251860e+08            28-Jan-15
512                2.305989e+08             3.122961e+08  2015-09-09 00:00:00
553                1.668235e+08             2.970025e+08  2015-03-18 00:00:00
578                1.028478e+08             2.871441e+08  2015-05-07 00:00:00
637                2.581246e+08             2.593684e+08            17-Dec-15
645                2.549816e+08             2.562839e+08            13-Aug-03
678                1.160547e+08             2.462331e+08  2015-10-29 00:00:00
688                1.661272e+08             2.448748e+08  2015-07-16 00:00:00
696                9.242900e+07             2.427861e+08  2002-11-08 00:00:00
720                1.248405e+08             2.356662e+08  2015-05-21 00:00:00
724                1.489116e+08             2.347986e+08  1999-06-25 00:00:00
743                2.268293e+08             2.281229e+08  2007-02-14 00:00:00
803                1.343872e+08             2.158636e+08  2015-06-19 00:00:00
843                1.155993e+08             2.090357e+08  2015-05-20 00:00:00
876                1.599453e+08             2.034276e+08  2015-09-10 00:00:00
884                4.043721e+07             2.016350e+08            14-Aug-15
919                1.188000e+08             1.945647e+08  2015-09-24 00:00:00
955                1.866998e+08             1.867980e+08  2005-02-02 00:00:00
970                1.365000e+08             1.838877e+08  2015-02-04 00:00:00

                                                 Genre Running Time License
4                    ['Action', 'Adventure', 'Sci-Fi']  2 hr 18 min   PG-13
7                    ['Action', 'Adventure', 'Sci-Fi']   2 hr 4 min   PG-13
10                     ['Action', 'Crime', 'Thriller']  2 hr 17 min   PG-13
14                   ['Action', 'Adventure', 'Sci-Fi']  2 hr 21 min   PG-13
25   ['Adventure', 'Animation', 'Comedy', 'Crime', ...  1 hr 31 min      PG
77                 ['Action', 'Adventure', 'Thriller']  2 hr 28 min   PG-13
86   ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 35 min      PG
149                ['Action', 'Adventure', 'Thriller']  2 hr 11 min   PG-13
162      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 17 min   PG-13
167                   ['Adventure', 'Drama', 'Sci-Fi']  2 hr 24 min   PG-13
194                   ['Drama', 'Romance', 'Thriller']   2 hr 5 min       R
212  ['Adventure', 'Drama', 'Family', 'Fantasy', 'R...  1 hr 45 min      PG
218        ['Action', 'Adventure', 'Drama', 'Western']  2 hr 36 min       R
232                     ['Action', 'Comedy', 'Sci-Fi']  1 hr 57 min   PG-13
260  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 29 min      PG
264                ['Action', 'Adventure', 'Thriller']  1 hr 54 min   PG-13
299      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']   2 hr 6 min   PG-13
361                             ['Action', 'Thriller']   2 hr 8 min   PG-13
363  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 34 min      PG
375      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']         2 hr       R
473                  ['Adventure', 'Comedy', 'Sci-Fi']  1 hr 48 min     NaN
488  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 32 min      PG
512      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  2 hr 11 min   PG-13
553      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  1 hr 59 min   PG-13
578                                ['Comedy', 'Music']  1 hr 55 min   PG-13
637  ['Action', 'Adventure', 'Drama', 'Fantasy', 'H...   2 hr 7 min     NaN
645                   ['Drama', 'Mystery', 'Thriller']  1 hr 48 min   PG-13
678  ['Adventure', 'Animation', 'Comedy', 'Drama', ...  1 hr 28 min       G
688          ['Action', 'Comedy', 'Fantasy', 'Sci-Fi']  1 hr 45 min   PG-13
696                                 ['Drama', 'Music']  1 hr 50 min       R
720                               ['Action', 'Comedy']         2 hr       R
724                                ['Comedy', 'Drama']  1 hr 33 min   PG-13
743                  ['Action', 'Fantasy', 'Thriller']  1 hr 50 min   PG-13
803                                         ['Comedy']  1 hr 55 min       R
843  ['Action', 'Adventure', 'Family', 'Fantasy', '...  2 hr 10 min      PG
876  ['Action', 'Adventure', 'Biography', 'Drama', ...   2 hr 1 min   PG-13
884         ['Biography', 'Drama', 'History', 'Music']  2 hr 27 min       R
919                                ['Comedy', 'Drama']   2 hr 1 min   PG-13
955         ['Biography', 'Drama', 'Music', 'Romance']  2 hr 16 min   PG-13
970                  ['Action', 'Adventure', 'Sci-Fi']   2 hr 7 min   PG-13

In [61]:
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2018)]

In [70]:
print(filtered_df)

     Unnamed: 0                                       Title  \
4             4  Star Wars: Episode VII - The Force Awakens
5             5                      Avengers: Infinity War
7             7                              Jurassic World
10           10                                   Furious 7
14           14                     Avengers: Age of Ultron
..          ...                                         ...
973         973                                      Storks
975         975                      The Hitman's Bodyguard
986         986                     From Vegas to Macau III
996         996                              Daddy's Home 2
997         997                               Hacksaw Ridge

                                            Movie Info    Year  \
4    As a new threat to the galaxy rises, Rey, a de...  2015.0
5    The Avengers and their allies must be willing ...  2018.0
7    A new theme park, built on the original site o...  2015.0
10   Deckard Shaw seeks revenge against Dominic Tor...  2015.0
14   When Tony Stark and Bruce Banner try to jump-s...  2015.0
..                                                 ...     ...
973  Storks have moved on from delivering babies to...  2016.0
975  One of the world's top bodyguards gets a new c...  2017.0
986  Ken is holding a wedding ceremony in Macau for...  2016.0
996  Having finally gotten used to each other's exi...  2017.0
997  World War II American Army Medic Desmond T. Do...  2016.0

                             Distributor              Budget (in $)  \
4    Walt Disney Studios Motion Pictures                  245000000
5    Walt Disney Studios Motion Pictures  April 25 2018 (APAC EMEA)
7                     Universal Pictures                  150000000
10                    Universal Pictures                  190000000
14   Walt Disney Studios Motion Pictures                  250000000
..                                   ...                        ...
973                         Warner Bros.                   70000000
975                            Lionsgate                   30000000
986              February 4, 2016 (APAC)                   24000000
996                   Paramount Pictures                   69000000
997                            Lionsgate                   40000000

    Domestic Opening (in $)  Domestic Sales (in $)  \
4                 247966675            936662225.0
5                 257698183            678815482.0
7                 208806270            653406625.0
10                147187040            353007020.0
14                191271109            459005868.0
..                      ...                    ...
973                21311407             72800603.0
975                21384504             75468583.0
986             1 hr 53 min            181732879.0
996                29651193            104029443.0
997                15190758             67209615.0

     International Sales (in $)  World Wide Sales (in $)         Release Date  \
4                  1.134648e+09             2.071310e+09            16-Dec-15
5                  1.373600e+09             2.052415e+09            16-Dec-15
7                  1.018131e+09             1.671537e+09  2015-06-10 00:00:00
10                 1.162334e+09             1.515341e+09             1-Apr-15
14                 9.460122e+08             1.405018e+09            22-Apr-15
..                          ...                      ...                  ...
973                1.107097e+08             1.835103e+08  2016-09-22 00:00:00
975                1.079601e+08             1.834287e+08            16-Aug-17
986                1.817329e+08             1.820166e+08  1995-06-02 00:00:00
996                7.658438e+07             1.806138e+08  2017-11-09 00:00:00
997                1.133540e+08             1.805636e+08  2016-11-03 00:00:00

                                                 Genre Running Time License
4                    ['Action', 'Adventure', 'Sci-Fi']  2 hr 18 min   PG-13
5                    ['Action', 'Adventure', 'Sci-Fi']  2 hr 18 min   PG-13
7                    ['Action', 'Adventure', 'Sci-Fi']   2 hr 4 min   PG-13
10                     ['Action', 'Crime', 'Thriller']  2 hr 17 min   PG-13
14                   ['Action', 'Adventure', 'Sci-Fi']  2 hr 21 min   PG-13
..                                                 ...          ...     ...
973  ['Adventure', 'Animation', 'Comedy', 'Family',...  1 hr 27 min      PG
975          ['Action', 'Comedy', 'Crime', 'Thriller']  1 hr 58 min       R
986                               ['Drama', 'Romance']  2 hr 15 min   PG-13
996                                         ['Comedy']  1 hr 40 min   PG-13
997           ['Biography', 'Drama', 'History', 'War']  2 hr 19 min       R

[190 rows x 14 columns]

In [ ]:
#llamar librerias de R
#llamar diplayer para iniciar, ty tratamiento de datos..

In [91]:
result = df.loc[df.groupby(['Year', 'Distributor'])['World_Wide_Sales_in_$'].idxmax()]

print(result)

KeyError: ignored